/**
 * giojs-core/src/standalone-gen.ts
 *
 * Generates the standalone worker entry module: static imports for every
 * discovered app module plus a registry literal handed to
 * runStandaloneServer(). The emitted source is the esbuild entry for
 * `gio build standalone`, so imports use absolute forward-slashed paths that
 * resolve identically on Windows and POSIX.
 */
import { resolve, sep } from 'node:path';

export interface StandaloneEntrySpec {
  /** Absolute path to giojs-core's standalone-entry.ts. */
  entryModulePath: string;
  routes: Array<{ pattern: string; filePath: string }>;
  layouts: Array<{ prefix: string; filePath: string }>;
  routeFiles: Array<{ pattern: string; filePath: string }>;
  notFoundPath?: string;
  errorPath?: string;
  configPath?: string;
  middlewarePath?: string;
  /** Route pattern → prebuilt hydration chunk URL. */
  clientScripts: Record<string, string>;
}

/** Forward-slashed absolute path, quoted for use inside an import statement. */
function moduleSpecifier(filePath: string): string {
  return JSON.stringify(resolve(filePath).split(sep).join('/'));
}

/** Emit the generated entry module source for `spec`. */
export function generateStandaloneEntry(spec: StandaloneEntrySpec): string {
  const imports: string[] = [
    `import { runStandaloneServer } from ${moduleSpecifier(spec.entryModulePath)};`,
  ];
  const routeEntries: string[] = [];
  spec.routes.forEach((route, index) => {
    imports.push(`import * as gioPage${index} from ${moduleSpecifier(route.filePath)};`);
    routeEntries.push(
      `    { pattern: ${JSON.stringify(route.pattern)}, filePath: ${JSON.stringify(route.filePath)}, module: gioPage${index} },`,
    );
  });
  const layoutEntries: string[] = [];
  spec.layouts.forEach((layout, index) => {
    imports.push(`import * as gioLayout${index} from ${moduleSpecifier(layout.filePath)};`);
    layoutEntries.push(
      `    { prefix: ${JSON.stringify(layout.prefix)}, filePath: ${JSON.stringify(layout.filePath)}, module: gioLayout${index} },`,
    );
  });
  const routeFileEntries: string[] = [];
  spec.routeFiles.forEach((routeFile, index) => {
    imports.push(`import * as gioRoute${index} from ${moduleSpecifier(routeFile.filePath)};`);
    routeFileEntries.push(
      `    { pattern: ${JSON.stringify(routeFile.pattern)}, filePath: ${JSON.stringify(routeFile.filePath)}, module: gioRoute${index} },`,
    );
  });

  const specialPageFields: string[] = [];
  if (spec.notFoundPath !== undefined) {
    imports.push(`import * as gioNotFound from ${moduleSpecifier(spec.notFoundPath)};`);
    specialPageFields.push('notFound: gioNotFound');
  }
  if (spec.errorPath !== undefined) {
    imports.push(`import * as gioError from ${moduleSpecifier(spec.errorPath)};`);
    specialPageFields.push('error: gioError');
  }

  const registryFields: string[] = [
    `  routes: [\n${routeEntries.join('\n')}\n  ],`,
    `  layouts: [\n${layoutEntries.join('\n')}\n  ],`,
    `  routeFiles: [\n${routeFileEntries.join('\n')}\n  ],`,
  ];
  if (specialPageFields.length > 0) {
    registryFields.push(`  specialPages: { ${specialPageFields.join(', ')} },`);
  }
  if (spec.configPath !== undefined) {
    imports.push(`import * as gioConfig from ${moduleSpecifier(spec.configPath)};`);
    registryFields.push('  config: gioConfig.default,');
  }
  if (spec.middlewarePath !== undefined) {
    imports.push(`import * as gioMiddleware from ${moduleSpecifier(spec.middlewarePath)};`);
    registryFields.push('  middleware: gioMiddleware.default,');
  }
  registryFields.push(`  clientScripts: ${JSON.stringify(spec.clientScripts, null, 2).replace(/\n/g, '\n  ')},`);

  return `// Generated by \`gio build standalone\` - do not edit.
${imports.join('\n')}

await runStandaloneServer({
${registryFields.join('\n')}
});
`;
}
