/**
 * giojs-core/src/typed-routes.ts
 *
 * Generates <projectRoot>/.gio/routes.d.ts from the discovered route
 * patterns. The file augments '@gio.js/react' via declaration merging so
 * href('/posts/:id', { id }) autocompletes and typechecks with zero
 * annotations in app code. Regenerated at every boot; the dev watcher
 * restarts the worker on file changes, which keeps it fresh.
 *
 * It also references .gio/css-modules.d.ts, which types CSS imports
 * (`import styles from './x.module.css'`): projects that include
 * routes.d.ts - every scaffolded one - get both. The wildcard module
 * declarations live in their own file because routes.d.ts is a module,
 * where `declare module '*.css'` would be read as an augmentation and
 * silently ignored.
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

/** File name of the CSS declarations, next to routes.d.ts. */
export const CSS_TYPES_FILE = 'css-modules.d.ts';

/**
 * .gio/css-modules.d.ts: a CSS Module's default export is its class map
 * (css-modules.ts), a global stylesheet exports nothing. `*.module.css`
 * comes first - TypeScript takes the first of equally specific patterns.
 */
export const CSS_MODULE_TYPES = [
  '/**',
  ` * .gio/${CSS_TYPES_FILE}`,
  ' *',
  ' * Generated by GioJS: types for CSS imports. Referenced by routes.d.ts.',
  ' * Do not edit - regenerated on every server start.',
  ' */',
  "declare module '*.module.css' {",
  '  const classes: { readonly [className: string]: string };',
  '  export default classes;',
  '}',
  "declare module '*.css' {}",
  '',
].join('\n');

const IDENTIFIER_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function escapeSingleQuoted(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

interface ParamSpec {
  name: string;
  /** Optional catch-all (`*name?`): may be omitted or empty. */
  optional: boolean;
}

function paramSpecs(pattern: string): ParamSpec[] {
  const params: ParamSpec[] = [];
  for (const segment of pattern.split('/')) {
    if (segment.startsWith(':') || segment.startsWith('*')) {
      const optional = segment.startsWith('*') && segment.endsWith('?');
      const name = optional ? segment.slice(1, -1) : segment.slice(1);
      if (name.length > 0) {
        params.push({ name, optional });
      }
    }
  }
  return params;
}

function paramsType(pattern: string): string {
  const params = paramSpecs(pattern);
  if (params.length === 0) {
    return 'Record<string, never>';
  }
  // Catch-all values are one string with '/' separators ("a/b"), the same
  // shape getServerSideProps receives in ctx.params.
  const fields = params.map(({ name, optional }) => {
    const key = IDENTIFIER_RE.test(name) ? name : `'${escapeSingleQuoted(name)}'`;
    return `${key}${optional ? '?' : ''}: string`;
  });
  return `{ ${fields.join('; ')} }`;
}

export function generateRouteTypes(patterns: string[]): string {
  const uniquePatterns = [...new Set(patterns)].sort();
  const entries = uniquePatterns.map(
    pattern => `    '${escapeSingleQuoted(pattern)}': ${paramsType(pattern)};`,
  );
  return [
    '/**',
    ' * .gio/routes.d.ts',
    ' *',
    ' * Generated by GioJS from the discovered route patterns.',
    ' * Do not edit - regenerated on every server start.',
    ' */',
    `/// <reference path="./${CSS_TYPES_FILE}" />`,
    "declare module '@gio.js/react' {",
    '  interface GioRegisteredRoutes {',
    ...entries,
    '  }',
    '}',
    'export {};',
    '',
  ].join('\n');
}

/** Write `content` to `path` unless it already holds exactly that. */
async function writeIfChanged(path: string, content: string): Promise<boolean> {
  let currentContent: string | null = null;
  try {
    currentContent = await readFile(path, 'utf8');
  } catch {
    currentContent = null;
  }
  if (currentContent === content) {
    return false;
  }
  await writeFile(path, content, 'utf8');
  return true;
}

/**
 * Writes routes.d.ts and css-modules.d.ts under <projectRoot>/.gio. Skips
 * a write when the content is unchanged so tsc --watch does not churn on
 * every boot. Returns true when either file was created or rewritten.
 */
export async function writeRouteTypes(
  projectRoot: string,
  patterns: string[],
): Promise<boolean> {
  const gioDir = join(projectRoot, '.gio');
  await mkdir(gioDir, { recursive: true });
  // The referenced file first, so routes.d.ts never points at a missing one.
  const wroteCss = await writeIfChanged(join(gioDir, CSS_TYPES_FILE), CSS_MODULE_TYPES);
  const wroteRoutes = await writeIfChanged(join(gioDir, 'routes.d.ts'), generateRouteTypes(patterns));
  return wroteCss || wroteRoutes;
}
