/**
 * giojs-core/src/typed-routes.ts
 *
 * Generates <projectRoot>/.gio/routes.d.ts from the discovered route
 * patterns. The file augments '@gio.js/react' via declaration merging so
 * href('/posts/:id', { id }) autocompletes and typechecks with zero
 * annotations in app code. Regenerated at every boot; the dev watcher
 * restarts the worker on file changes, which keeps it fresh.
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const IDENTIFIER_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function escapeSingleQuoted(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

interface ParamSpec {
  name: string;
  /** Optional catch-all (`*name?`): may be omitted or empty. */
  optional: boolean;
}

function paramSpecs(pattern: string): ParamSpec[] {
  const params: ParamSpec[] = [];
  for (const segment of pattern.split('/')) {
    if (segment.startsWith(':') || segment.startsWith('*')) {
      const optional = segment.startsWith('*') && segment.endsWith('?');
      const name = optional ? segment.slice(1, -1) : segment.slice(1);
      if (name.length > 0) {
        params.push({ name, optional });
      }
    }
  }
  return params;
}

function paramsType(pattern: string): string {
  const params = paramSpecs(pattern);
  if (params.length === 0) {
    return 'Record<string, never>';
  }
  // Catch-all values are one string with '/' separators ("a/b"), the same
  // shape getServerSideProps receives in ctx.params.
  const fields = params.map(({ name, optional }) => {
    const key = IDENTIFIER_RE.test(name) ? name : `'${escapeSingleQuoted(name)}'`;
    return `${key}${optional ? '?' : ''}: string`;
  });
  return `{ ${fields.join('; ')} }`;
}

export function generateRouteTypes(patterns: string[]): string {
  const uniquePatterns = [...new Set(patterns)].sort();
  const entries = uniquePatterns.map(
    pattern => `    '${escapeSingleQuoted(pattern)}': ${paramsType(pattern)};`,
  );
  return [
    '/**',
    ' * .gio/routes.d.ts',
    ' *',
    ' * Generated by GioJS from the discovered route patterns.',
    ' * Do not edit - regenerated on every server start.',
    ' */',
    "declare module '@gio.js/react' {",
    '  interface GioRegisteredRoutes {',
    ...entries,
    '  }',
    '}',
    'export {};',
    '',
  ].join('\n');
}

/**
 * Writes routes.d.ts under <projectRoot>/.gio. Skips the write when the
 * content is unchanged so tsc --watch does not churn on every boot.
 * Returns true when the file was created or rewritten.
 */
export async function writeRouteTypes(
  projectRoot: string,
  patterns: string[],
): Promise<boolean> {
  const gioDir = join(projectRoot, '.gio');
  const typesPath = join(gioDir, 'routes.d.ts');
  const nextContent = generateRouteTypes(patterns);

  let currentContent: string | null = null;
  try {
    currentContent = await readFile(typesPath, 'utf8');
  } catch {
    currentContent = null;
  }
  if (currentContent === nextContent) {
    return false;
  }

  await mkdir(gioDir, { recursive: true });
  await writeFile(typesPath, nextContent, 'utf8');
  return true;
}
