/**
 * giojs-cli/test/next-config-converter.test.ts
 *
 * next.config → gio.toml: path syntax, redirects/rewrites/headers, images,
 * i18n, and the never-overwrite merge rules for an existing gio.toml.
 *   npm test
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildToml, convertConfigSource, convertPath, mergeToml, planToml } from '../dist/next-config-converter.js';

const here = dirname(fileURLToPath(import.meta.url));

test('convertPath maps path-to-regexp syntax to gio.toml patterns', () => {
  assert.deepEqual(convertPath('/blog/:slug', 'source'), { path: '/blog/:slug' });
  assert.deepEqual(convertPath('/docs/:path*', 'source'), { path: '/docs/*path' });
  assert.deepEqual(convertPath('/', 'source'), { path: '/' });
  assert.deepEqual(convertPath('/a/:rest+', 'source'), {
    path: '/a/*rest',
    note: '":rest+" (one or more segments) became "*rest", which also matches zero segments',
  });
  for (const bad of ['/a/:id?', '/a/:id(\\d+)', '/a/(.*)', '/post-:id', '/a/:path*/b', 'relative']) {
    assert.ok('error' in convertPath(bad, 'source'), bad);
  }
  assert.ok('error' in convertPath('https://example.com/:path*', 'destination'));
  assert.ok('error' in convertPath('/search?q=:q', 'destination'));
});

test('the legacy tests/fixtures next.config.js converts redirects, rewrites and images', async () => {
  const source = await readFile(join(here, '..', '..', '..', 'tests', 'fixtures', 'next.config.js'), 'utf8');
  const config = convertConfigSource(source, 'next.config.js');
  assert.deepEqual(config.entries.map(e => [e.name, Object.fromEntries(e.keys)]), [
    ['images.remote_patterns', { protocol: '"https"', hostname: '"cdn.example.com"', pathname: '"/images/*"' }],
    ['images.remote_patterns', { protocol: '"https"', hostname: '"**.cloudinary.com"' }],
    ['redirects', { from: '"/old-blog/:slug"', to: '"/blog/:slug"', status: '308' }],
    ['redirects', { from: '"/docs"', to: '"/documentation"', status: '307' }],
  ]);
  // The rewrite targets another host: skipped with a TODO, never approximated.
  assert.equal(config.todos.length, 1);
  assert.match(config.todos[0] ?? '', /rewrite \/api\/:path\* → http:\/\/internal-service:8080\/:path\* skipped: GioJS rewrites are internal/);
  assert.match(config.notes.join('\n'), /reactStrictMode/);
});

const RICH_CONFIG = `
const securityHeaders = [
  { key: 'X-Frame-Options', value: 'DENY' },
  { key: 'X-Content-Type-Options', value: 'nosniff' },
];

/** @type {import('next').NextConfig} */
const nextConfig = {
  basePath: '/app',
  trailingSlash: true,
  output: 'export',
  env: { API_URL: 'https://api.example.com' },
  webpack: (config) => config,
  i18n: { locales: ['en', 'de', 'fr'], defaultLocale: 'en', localeDetection: false },
  images: {
    remotePatterns: [
      { protocol: 'https', hostname: 'img.example.com', port: '8443' },
      { hostname: '*.example.org', pathname: '/a/**/b' },
      { protocol: 'https', hostname: 'assets.example.com', pathname: '/uploads/*' },
    ],
    deviceSizes: [640, 1080, 1920],
    imageSizes: [16, 64, 640],
  },
  async headers() {
    return [
      { source: '/:path*', headers: securityHeaders },
      { source: '/api/:path*', has: [{ type: 'header', key: 'x-internal' }], headers: [{ key: 'X-Internal', value: '1' }] },
    ];
  },
  async redirects() {
    return [
      { source: '/home', destination: '/', permanent: true },
      { source: '/legacy/:id(\\\\d+)', destination: '/items/:id', permanent: false },
      { source: '/a', destination: '/b/:missing', permanent: false },
      { source: '/moved', destination: '/new', statusCode: 301 },
      { source: '/twitter', destination: 'https://twitter.com/giojs', permanent: false },
    ];
  },
  rewrites: async () => ({
    beforeFiles: [{ source: '/feed', destination: '/api/feed' }],
    afterFiles: [{ source: '/docs/:slug+', destination: '/documentation/:slug' }],
    fallback: [{ source: '/:path*', destination: '/legacy/:path*' }],
  }),
};

export default withBundleAnalyzer(nextConfig);
`;

test('a rich next.config converts every supported setting and flags the rest', () => {
  const config = convertConfigSource(RICH_CONFIG, 'next.config.mjs');
  const toml = buildToml(config, 'shop');
  assert.equal(toml, [
    '# gio.toml - generated by create-giojs migrate from next.config.',
    '# Reference: https://giojs.com/docs/configuration',
    '',
    '[app]',
    'name = "shop"',
    '',
    '[server]',
    'host = "0.0.0.0"',
    'port = 3000',
    'http2 = true',
    '',
    ...config.todos.map(t => `# TODO(gio-migrate): ${t}`),
    '',
    '[i18n]',
    'locales = ["en", "de", "fr"]',
    'default_locale = "en"',
    'detect_from = ["path"]',
    '',
    '[images]',
    'allowed_widths = [16, 64, 640, 1080, 1920]',
    '',
    '# TODO(gio-migrate): pathname "/uploads/*" (one segment in Next.js) now allows any depth below /uploads/',
    '[[images.remote_patterns]]',
    'protocol = "https"',
    'hostname = "assets.example.com"',
    'pathname = "/uploads/*"',
    '',
    '[[headers]]',
    'path = "/*path"',
    'headers = { "X-Frame-Options" = "DENY", "X-Content-Type-Options" = "nosniff" }',
    '',
    '[[redirects]]',
    'from = "/home"',
    'to = "/"',
    'status = 308',
    '',
    '[[redirects]]',
    'from = "/moved"',
    'to = "/new"',
    'status = 301',
    '',
    '[[rewrites]]',
    'from = "/feed"',
    'to = "/api/feed"',
    '',
    '# TODO(gio-migrate): ":slug+" (one or more segments) became "*slug", which also matches zero segments',
    '[[rewrites]]',
    'from = "/docs/*slug"',
    'to = "/documentation/:slug"',
    '',
  ].join('\n'));

  const todos = config.todos.join('\n');
  for (const expected of [
    /basePath "\/app"/,
    /trailingSlash: true/,
    /env: move these values to \.env/,
    /webpack: GioJS bundles with esbuild/,
    /remote image pattern img\.example\.com:8443 skipped: gio\.toml remote_patterns have no port/,
    /remote image pattern \*\.example\.org skipped: pathname "\/a\/\*\*\/b" uses a glob/,
    /headers for \/api\/:path\* has has\/missing conditions/,
    /redirect \/legacy\/:id\(\\d\+\) → \/items\/:id skipped: segment ":id\(\\d\+\)" uses a regex/,
    /redirect \/a → \/b\/:missing skipped: the destination uses :missing, which the source doesn't capture/,
    /redirect \/twitter → https:\/\/twitter\.com\/giojs skipped: external destination/,
    /1 fallback rewrite\(s\) skipped/,
  ]) {
    assert.match(todos, expected);
  }
  assert.equal(config.staticExport, true);
  assert.deepEqual(config.envKeys, ['API_URL']);
  assert.match(config.notes.join('\n'), /wrapped in withBundleAnalyzer/);
});

test('a config that cannot be read statically produces a TODO, not a guess', () => {
  const config = convertConfigSource("module.exports = require('./config.json');\n", 'next.config.js');
  assert.deepEqual(config.entries, []);
  assert.match(config.todos[0] ?? '', /convert it by hand/);
});

test('mergeToml appends new tables and inserts keys into existing ones', () => {
  const existing = '[app]\nname = "x"\n\n[images]\nquality = 80\n\n[server]\nhost = "0.0.0.0"\nport = 3000\n';
  const config = convertConfigSource(
    "module.exports = { images: { deviceSizes: [640], domains: ['a.com'] }, i18n: { locales: ['en'], defaultLocale: 'en' }, redirects: async () => [{ source: '/a', destination: '/b', permanent: true }] };",
    'next.config.js',
  );
  const merged = mergeToml(existing, config);
  assert.ok('content' in merged);
  assert.equal(merged.content, [
    '[app]',
    'name = "x"',
    '',
    '[images]',
    'allowed_widths = [640]',
    'quality = 80',
    '',
    '[server]',
    'host = "0.0.0.0"',
    'port = 3000',
    '',
    '# ── Migrated from Next.js by create-giojs migrate (keys added to existing tables are listed in MIGRATION_REPORT.md) ──',
    '',
    '[i18n]',
    'locales = ["en"]',
    'default_locale = "en"',
    '',
    '[[images.remote_patterns]]',
    'protocol = "https"',
    'hostname = "a.com"',
    '',
    '[[redirects]]',
    'from = "/a"',
    'to = "/b"',
    'status = 308',
    '',
  ].join('\n'));
});

test('mergeToml refuses to define a key or table twice', () => {
  const config = convertConfigSource("module.exports = { images: { deviceSizes: [640] }, i18n: { locales: ['en'] } };", 'next.config.js');
  const clash = mergeToml('[images]\nallowed_widths = [100]\n', config);
  assert.deepEqual(clash, { conflict: 'gio.toml already sets [images] allowed_widths' });
  const inline = mergeToml('i18n = { locales = ["de"] }\n', config);
  assert.ok('conflict' in inline);
  const patterns = convertConfigSource("module.exports = { images: { domains: ['a.com'] } };", 'next.config.js');
  assert.ok('conflict' in mergeToml('[images]\nremote_patterns = []\n', patterns));
  const redirects = convertConfigSource("module.exports = { redirects: async () => [{ source: '/a', destination: '/b' }] };", 'next.config.js');
  assert.ok('conflict' in mergeToml('redirects = []\n', redirects));
});

test('planToml never overwrites: it creates, merges, or writes gio.migrated.toml', () => {
  const config = convertConfigSource("module.exports = { images: { deviceSizes: [640] } };", 'next.config.js');
  assert.equal(planToml(undefined, config, 'app').mode, 'created');
  const merged = planToml('[server]\nhost = "0.0.0.0"\nport = 3000\n', config, 'app');
  assert.equal(merged.mode, 'merged');
  assert.ok(merged.content.startsWith('[server]\nhost = "0.0.0.0"\nport = 3000\n'));
  const separate = planToml('[images]\nallowed_widths = [1]\n', config, 'app');
  assert.equal(separate.mode, 'separate');
  assert.equal(separate.target, 'gio.migrated.toml');
  assert.match(separate.content, /gio\.toml already sets \[images\] allowed_widths/);
  assert.match(separate.content, /\[images\]\nallowed_widths = \[640\]/);
  // A second migration never merges twice.
  assert.equal(planToml(merged.content, config, 'app').mode, 'separate');
});
