/**
 * packages/giojs-cli/src/migrate-report.ts
 *
 * MIGRATION_REPORT.md: every move, every change and every TODO the
 * migration produced, with file:line references into the migrated files
 * (TODO lines are read back from the planned output, so they are exact).
 */
import type { MigrationPlan, PlannedFile } from './migrate.js';
import { SERVER_ACTION_TODO_PREFIX } from './migrate-transforms.js';

export const REPORT_FILE = 'MIGRATION_REPORT.md';
export const REPORT_HEADER = '# GioJS migration report';

const ROUTER_LABEL: Record<MigrationPlan['router'], string> = {
  pages: 'pages router',
  app: 'app router',
  both: 'pages + app router',
  none: 'Next.js',
};

function code(text: string): string {
  return '`' + text.replace(/`/g, "'") + '`';
}

function fileLabel(file: PlannedFile): string {
  if (file.from !== undefined && file.from !== file.to) return `${code(file.to)} (moved from ${code(file.from)})`;
  if (file.mergedFrom !== undefined) return `${code(file.to)} (generated from ${file.mergedFrom.map(code).join(' + ')})`;
  return code(file.to);
}

export function buildReport(plan: MigrationPlan, date: Date): string {
  const textFiles = plan.files.filter(f => typeof f.content === 'string');
  const todos = [
    ...textFiles.flatMap(f => f.todos.map(t => ({ ref: `${f.to}:${t.line}`, message: t.message }))),
    ...plan.todos.map(t => ({ ref: t.file, message: t.message })),
  ];
  const moved = plan.files.filter(f => f.kind === 'moved');
  const modified = plan.files.filter(f => f.kind === 'modified');
  const created = plan.files.filter(f => f.kind === 'created');

  const lines: string[] = [
    REPORT_HEADER,
    '',
    `Generated by \`create-giojs migrate\` on ${date.toISOString().slice(0, 10)} for a Next.js ${ROUTER_LABEL[plan.router]} project.`,
    '',
    `**${todos.length} TODO${todos.length === 1 ? '' : 's'}** need a human (each one is also a \`TODO(gio-migrate)\` comment in the code, so \`grep -rn "TODO(gio-migrate)" .\` finds them). ` +
      `${modified.length} file${modified.length === 1 ? '' : 's'} changed in place, ${moved.length} moved, ${created.length + 1} created (this report included).`,
    '',
    '## Next steps',
    '',
    '1. `npm install` - the Next.js packages were swapped for `@gio.js/server` and `@gio.js/react`.',
    '2. Work through the TODOs below.',
    '3. `npx tsc --noEmit` to catch what the migration could not see (types from `next`, changed props).',
    '4. `npm run dev` and click through the app.',
    '5. Delete `next.config.*`, `next-env.d.ts` and `.next/` once everything works.',
    '',
    '## TODOs',
    '',
  ];
  if (todos.length === 0) lines.push('None - nothing needs manual work.');
  for (const todo of todos) lines.push(`- [ ] ${todo.ref !== undefined ? `${code(todo.ref)} - ` : ''}${todo.message}`);
  lines.push('');

  if (moved.length > 0) {
    lines.push('## Files moved', '', '| From | To |', '|------|----|');
    for (const f of moved) lines.push(`| ${code(f.from ?? '')} | ${code(f.to)} |`);
    for (const f of created.filter(c => c.mergedFrom !== undefined)) {
      lines.push(`| ${(f.mergedFrom ?? []).map(code).join(' + ')} | ${code(f.to)} |`);
    }
    lines.push('');
  }

  const withChanges = plan.files.filter(f => f.changes.length > 0);
  if (withChanges.length > 0) {
    lines.push('## Changes', '');
    for (const f of withChanges) {
      lines.push(`### ${fileLabel(f)}`, '');
      for (const c of f.changes) lines.push(`- ${c.line > 0 ? `${code(`${f.to}:${c.line}`)} ` : ''}${c.message}`);
      lines.push('');
    }
  }

  if (plan.config !== undefined) {
    const { source, converted, toml } = plan.config;
    lines.push(`## Configuration (${code(source)} → ${code(toml.target)})`, '');
    if (toml.mode === 'created') lines.push(`Created ${code('gio.toml')}.`);
    if (toml.mode === 'merged') lines.push(`Merged into the existing ${code('gio.toml')} (nothing in it was changed or removed).`);
    if (toml.mode === 'separate') {
      lines.push(`**Not merged:** ${toml.reason ?? 'merging was unsafe'}. The converted sections are in ${code(toml.target)}, which GioJS does not load - copy them into ${code('gio.toml')} by hand.`);
    }
    lines.push('');
    for (const c of converted.converted) lines.push(`- ${c}`);
    for (const n of converted.notes) lines.push(`- ${n}`);
    if (converted.envKeys.length > 0) {
      lines.push(`- env keys to move to \`.env\`: ${converted.envKeys.map(code).join(', ')} (browser code only sees \`GIO_PUBLIC_*\` variables)`);
    }
    lines.push('');
  }

  if (plan.fonts.length > 0) {
    lines.push(
      '## Fonts',
      '',
      'GioJS self-hosts fonts declared in `gio.toml` (served from `/_gio/fonts`, preloaded automatically). ' +
        'Add one `[[fonts]]` entry per weight/style with the URL of the `.woff2` file, then set `font-family` in your CSS:',
      '',
      '```toml',
    );
    const seen = new Set<string>();
    for (const font of plan.fonts) {
      for (const weight of font.weights) {
        for (const style of font.styles) {
          const key = `${font.family}|${weight}|${style}`;
          if (seen.has(key)) continue;
          seen.add(key);
          const url = font.source === 'local' && font.files[0] !== undefined
            ? `"/fonts/${font.files[0].replace(/^.*\//, '')}"  # copy ${font.files[0]} (relative to ${font.filePath}) into public/fonts/`
            : `"https://..."  # the .woff2 URL (e.g. from the Google Fonts CSS for ${font.family})`;
          lines.push('[[fonts]]', `family = ${JSON.stringify(font.family)}`, `url = ${url}`);
          lines.push(`weight = ${/^\d+$/.test(weight) ? weight : '400  # was ' + JSON.stringify(weight)}`, `style = ${JSON.stringify(style)}`, '');
        }
      }
    }
    lines.pop();
    lines.push('```', '');
  }

  if (todos.some(t => t.message.startsWith(SERVER_ACTION_TODO_PREFIX))) lines.push(...SERVER_ACTIONS_SECTION);

  if (plan.notes.length > 0) {
    lines.push('## Notes', '');
    for (const n of plan.notes) lines.push(`- ${n}`);
    lines.push('');
  }
  lines.push(
    '## What GioJS does differently',
    '',
    '- Every page hydrates in the browser: there are no React Server Components or `\'use client\'`. Server data comes from `getServerSideProps` (with `export const revalidate = N` to cache the result in Rust).',
    '- Forms post to the page\'s own `export async function action(req)` (rendered with `<GioForm>` from `@gio.js/react`) instead of Server Actions; other mutations are `route.ts` handlers.',
    '- `export const metadata`, `generateMetadata(ctx, { props })`, `app/sitemap.ts`, `app/robots.ts` and `app/manifest.ts` work like in Next.js. Set `GIO_SITE_URL` (or `metadataBase`) so relative URLs become absolute.',
    '- Caching is per page, in Rust: `export const revalidate` and `export const tags`, purged with `revalidatePath()` / `revalidateTag()` from `@gio.js/core`. `fetch()` has no data cache.',
    '- The root `app/layout` renders `<html>`, `<head>` and `<body>` on the server only - it is never hydrated.',
    '- Redirects, rewrites, headers and auth guards run in the Rust server from `gio.toml` / `middleware.ts`, before any page code.',
    '- Client bundles are built with esbuild; there is no webpack or SWC configuration.',
    '',
  );
  return lines.join('\n');
}

/** How a Server Action becomes a page action; in the report when the code has Server Actions. */
const SERVER_ACTIONS_SECTION = [
  '## Server Actions',
  '',
  'GioJS has no Server Actions. A form\'s action becomes the page\'s `action` export - a POST to the page runs it - and `<GioForm>` posts to it ' +
    '(a real `<form method="post">`, so it works without JavaScript too; once hydrated it submits through the client router). ' +
    'The migration turned every `<form action={serverAction}>` it recognized into `<GioForm>`; move each action\'s body into the page:',
  '',
  '```tsx',
  '// app/posts/new/page.tsx',
  "import { redirect, revalidatePath, type ActionArgs, type WithActionData } from '@gio.js/core';",
  "import { GioForm, useGioFormState } from '@gio.js/react';",
  '',
  '// Was: async function createPost(formData: FormData) { \'use server\'; ... }',
  'export async function action(req: ActionArgs) {',
  '  const form = await req.formData();',
  "  const title = String(form.get('title') ?? '').trim();",
  "  if (title === '') return { status: 422, data: { error: 'Title is required' } }; // re-renders the page with actionData",
  '  await db.posts.create({ title });',
  "  await revalidatePath('/posts');",
  "  return redirect('/posts'); // 303 See Other",
  '}',
  '',
  'function Submit() {',
  '  const { pending } = useGioFormState(); // was useFormStatus()',
  "  return <button disabled={pending}>{pending ? 'Saving...' : 'Create'}</button>;",
  '}',
  '',
  'export default function NewPost({ actionData }: WithActionData<typeof action>) {',
  '  return (',
  '    <GioForm> {/* was <form action={createPost}> */}',
  '      <input name="title" />',
  '      {actionData?.error && <p role="alert">{actionData.error}</p>}',
  '      <Submit />',
  '    </GioForm>',
  '  );',
  '}',
  '```',
  '',
  'Arguments a Server Action got through `.bind(null, id)` become hidden `<input name="id">` fields; several actions on one page become one ' +
    '`action` that branches on a submit button\'s `name="intent"` value. An action called from code rather than a form becomes a `route.ts` handler:',
  '',
  '```ts',
  '// app/api/posts/route.ts - called with fetch(\'/api/posts\', { method: \'POST\', headers: { \'content-type\': \'application/json\' }, body: JSON.stringify(post) })',
  "import type { GioRequest } from '@gio.js/core';",
  '',
  'export async function POST(req: GioRequest) {',
  '  const post = req.json<{ title: string }>();',
  '  return Response.json(await db.posts.create(post), { status: 201 });',
  '}',
  '```',
  '',
  'Every unsafe request is CSRF-checked by the Rust server (cross-site form posts get a 403), but an action is still a public endpoint: validate every field.',
  '',
];
