/**
 * packages/giojs-cli/src/next-config-converter.ts
 *
 * Best-effort conversion of next.config.js patterns to gio.toml.
 * Text-based extraction — does not execute user code.
 * Anything that cannot be auto-converted is listed in migration-report.md.
 */
import { readFile, writeFile } from 'fs/promises';
import { join, dirname } from 'path';

interface RemotePattern {
  protocol?: string;
  hostname: string;
  pathname?: string;
}

interface Redirect {
  source: string;
  destination: string;
  permanent?: boolean;
}

interface Rewrite {
  source: string;
  destination: string;
}

interface ExtractedConfig {
  remotePatterns: RemotePattern[];
  redirects: Redirect[];
  rewrites: Rewrite[];
  unrecognized: string[];
}

function extractStringProp(obj: string, key: string): string | undefined {
  const m = new RegExp(`${key}\\s*:\\s*['"]([^'"]+)['"]`).exec(obj);
  return m?.[1];
}

function extractBoolProp(obj: string, key: string): boolean | undefined {
  const m = new RegExp(`${key}\\s*:\\s*(true|false)`).exec(obj);
  if (!m) return undefined;
  return m[1] === 'true';
}

function extractObjectBlocks(text: string, key: string): string[] {
  // Find the array under 'key' and extract each {…} block
  const keyIdx = text.indexOf(key);
  if (keyIdx === -1) return [];

  let depth = 0;
  let inArray = false;
  const blocks: string[] = [];
  let blockStart = -1;

  for (let i = keyIdx; i < text.length; i++) {
    const ch = text[i];
    if (!inArray && ch === '[') { inArray = true; continue; }
    if (!inArray) continue;

    if (ch === '{') {
      if (depth === 0) blockStart = i;
      depth++;
    } else if (ch === '}') {
      depth--;
      if (depth === 0 && blockStart !== -1) {
        blocks.push(text.slice(blockStart, i + 1));
        blockStart = -1;
      }
    } else if (ch === ']' && depth === 0) {
      break;
    }
  }

  return blocks;
}

function extractConfig(source: string): ExtractedConfig {
  const remotePatterns: RemotePattern[] = [];
  const redirects: Redirect[] = [];
  const rewrites: Rewrite[] = [];
  const unrecognized: string[] = [];

  // Remote patterns
  for (const block of extractObjectBlocks(source, 'remotePatterns')) {
    const hostname = extractStringProp(block, 'hostname');
    if (hostname) {
      remotePatterns.push({
        protocol: extractStringProp(block, 'protocol'),
        hostname,
        pathname: extractStringProp(block, 'pathname'),
      });
    }
  }

  // Redirects
  for (const block of extractObjectBlocks(source, 'redirects')) {
    const source_ = extractStringProp(block, 'source');
    const destination = extractStringProp(block, 'destination');
    if (source_ && destination) {
      redirects.push({
        source: source_,
        destination,
        permanent: extractBoolProp(block, 'permanent'),
      });
    }
  }

  // Rewrites
  for (const block of extractObjectBlocks(source, 'rewrites')) {
    const source_ = extractStringProp(block, 'source');
    const destination = extractStringProp(block, 'destination');
    if (source_ && destination) {
      rewrites.push({ source: source_, destination });
    }
  }

  // Detect unrecognized keys that need manual migration
  const knownKeys = ['images', 'redirects', 'rewrites', 'reactStrictMode', 'output'];
  const topLevelKeys = [...source.matchAll(/^\s{0,2}(\w+)\s*[:{(]/gm)].map(m => m[1] ?? '');
  for (const key of topLevelKeys) {
    if (!knownKeys.includes(key) && key !== 'module' && key !== 'const' && key !== 'export') {
      unrecognized.push(key);
    }
  }

  return { remotePatterns, redirects, rewrites, unrecognized };
}

function buildToml(config: ExtractedConfig): string {
  const lines: string[] = [
    '# gio.toml — generated by gio-migrate',
    '# Review this file and adjust values before deploying.',
    '',
    '[app]',
    'name = "my-app"',
    'router = "app"',
    '',
    '[server]',
    'host = "0.0.0.0"',
    'port = 3000',
    'http2 = true',
    '',
    '[cache]',
    'memory_mb = 50',
    '',
    '[compression]',
    'enabled = true',
    '',
    '[prefetch]',
    'strategy = "hover"',
    '',
  ];

  if (config.remotePatterns.length > 0) {
    lines.push('[images]');
    lines.push('quality = 75');
    lines.push('');
    for (const p of config.remotePatterns) {
      lines.push('[[images.remotePatterns]]');
      if (p.protocol) lines.push(`protocol = "${p.protocol}"`);
      lines.push(`hostname = "${p.hostname}"`);
      if (p.pathname) lines.push(`pathname = "${p.pathname}"`);
      lines.push('');
    }
  }

  for (const r of config.redirects) {
    lines.push('[[redirects]]');
    lines.push(`from = "${r.source}"`);
    lines.push(`to = "${r.destination}"`);
    lines.push(`status = ${r.permanent === true ? 301 : 302}`);
    lines.push('');
  }

  for (const r of config.rewrites) {
    lines.push('[[rewrites]]');
    lines.push(`from = "${r.source}"`);
    lines.push(`to = "${r.destination}"`);
    lines.push('');
  }

  return lines.join('\n');
}

function buildReport(
  configPath: string,
  config: ExtractedConfig,
  tomlPath: string,
): string {
  const date = new Date().toISOString().slice(0, 10);
  const lines: string[] = [
    '# Migration Report',
    '',
    `Generated: ${date}  `,
    `Source: \`${configPath}\`  `,
    `Output: \`${tomlPath}\``,
    '',
    '## Auto-converted',
    '',
    '| Setting | Count |',
    '|---------|-------|',
    `| \`images.remotePatterns\` | ${config.remotePatterns.length} |`,
    `| \`redirects\` | ${config.redirects.length} |`,
    `| \`rewrites\` | ${config.rewrites.length} |`,
    '',
  ];

  if (config.unrecognized.length > 0) {
    lines.push('## Manual migration required');
    lines.push('');
    lines.push('The following `next.config.js` keys were not auto-converted:');
    lines.push('');
    for (const key of [...new Set(config.unrecognized)]) {
      lines.push(`- \`${key}\` — review Next.js docs and add equivalent config to \`gio.toml\``);
    }
    lines.push('');
  }

  lines.push('## Notes');
  lines.push('');
  lines.push('- `next/font` declarations must be moved to `[[fonts]]` in `gio.toml`');
  lines.push('- `headers()` is handled via `[security]` in gio.toml (security headers are injected automatically)');
  lines.push('- Custom webpack config has no equivalent — GioJS uses SWC for compilation');
  lines.push('- `experimental.*` flags have no equivalent in GioJS v0.1');

  return lines.join('\n') + '\n';
}

export async function convertNextConfig(configPath: string): Promise<void> {
  const source = await readFile(configPath, 'utf8');
  const config = extractConfig(source);
  const outDir = dirname(configPath);
  const tomlPath = join(outDir, 'gio.toml');
  const reportPath = join(outDir, 'migration-report.md');

  await writeFile(tomlPath, buildToml(config), 'utf8');
  await writeFile(reportPath, buildReport(configPath, config, tomlPath), 'utf8');

  console.log(`\nConfig conversion complete:`);
  console.log(`  gio.toml          → ${tomlPath}`);
  console.log(`  migration-report  → ${reportPath}`);
  if (config.unrecognized.length > 0) {
    console.log(`\n  ${config.unrecognized.length} key(s) need manual migration — see migration-report.md`);
  }
}
